version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"  # Web UI
    volumes:
      - qdrant-storage:/qdrant/storage
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  qdrant-storage:
    driver: local